# From rest-client environment
# @auth0Domain = {{auth0Domain}}
# @auth0ClientId = {{auth0ClientId}}
# @auth0ClientSecret = {{auth0ClientSecret}}
# @audience = {{auth0Audience}}
# @auth0GrantType = {{auth0GrantType}}
# @apiBaseUrl = {{apiBaseUrl}}

# @name auth
POST {{auth0Domain}}/oauth/token HTTP/1.1
Content-Type: application/json

{
    "client_id":"{{auth0ClientId}}",
    "client_secret":"{{auth0ClientSecret}}",
    "audience":"{{auth0Audience}}",
    "grant_type":"{{auth0GrantType}}"
}

###

@authToken = {{auth.response.body.access_token}}

# @name getAllWishlists
GET {{apiBaseUrl}}/wishlists HTTP/1.1
Authorization: Bearer {{authToken}}
###

# @name createWishlist
POST {{apiBaseUrl}}/wishlists HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Fake wishlist",
    "description": "Fake description"
}
###

@wishlistId = {{createWishlist.response.body.$._id}}

# @name getCreatedWishlist
GET {{apiBaseUrl}}/wishlists/{{wishlistId}} HTTP/1.1
Authorization: Bearer {{authToken}}
###

## @name createWish
POST {{apiBaseUrl}}/wishlists/{{wishlistId}}/wishes HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "wishlistId": "{{wishlistId}}",
    "title": "Fake wish # 1"
}
###

## @name getWishes
GET {{apiBaseUrl}}/wishlists/{{wishlistId}}/wishes HTTP/1.1
Authorization: Bearer {{authToken}}
###

@wishId = {{getWishes.response.body.$[0]._id}}

## @name deleteWish
DELETE {{apiBaseUrl}}/wishlists/{{wishlistId}}/wishes/{{wishId}} HTTP/1.1
Authorization: Bearer {{authToken}}
###



# @name deleteCreatedWishlist
DELETE  {{apiBaseUrl}}/wishlists/{{wishlistId}} HTTP/1.1
Authorization: Bearer {{authToken}}
###