@authBaseUrl = https://dev-portal.eu.auth0.com
@clientId = gMBKKq8uWxZ6DnJqoTGeANSnrK21NygK
@clientSecret = Bu7gq0IlI_sGKshhPxDIe5Szn1ZkJPIyym_uqDmtC0fDLxnvm8sg7HQZtkpTEcZu
@audience = https://stonefree-portal-auth.com
@grantType = client_credentials
@baseUrl = http://localhost:3333/api

# @name auth
POST {{authBaseUrl}}/oauth/token HTTP/1.1
Content-Type: application/json

{
    "client_id":"{{clientId}}",
    "client_secret":"{{clientSecret}}",
    "audience":"{{audience}}",
    "grant_type":"{{grantType}}"
}

###

@authToken = {{auth.response.body.access_token}}

# @name getAllWishlists
GET {{baseUrl}}/wishlists HTTP/1.1
Authorization: Bearer {{authToken}}
###

# @name createWishlist
POST {{baseUrl}}/wishlists HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Fake wishlist",
    "description": "Fake description"
}
###

@wishlistId = {{createWishlist.response.body.$._id}}

# @name getCreatedWishlist
GET {{baseUrl}}/wishlists/{{wishlistId}} HTTP/1.1
Authorization: Bearer {{authToken}}
###

## @name createWish
POST {{baseUrl}}/wishlists/{{wishlistId}}/wishes HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "wishlistId": "{{wishlistId}}",
    "title": "Fake wish # 1"
}
###

## @name getWishes
GET {{baseUrl}}/wishlists/{{wishlistId}}/wishes HTTP/1.1
Authorization: Bearer {{authToken}}
###

@wishId = {{getWishes.response.body.$[0]._id}}

## @name deleteWish
DELETE {{baseUrl}}/wishlists/{{wishlistId}}/wishes/{{wishId}} HTTP/1.1
Authorization: Bearer {{authToken}}
###



# @name deleteCreatedWishlist
DELETE  {{baseUrl}}/wishlists/{{wishlistId}} HTTP/1.1
Authorization: Bearer {{authToken}}
###